[package]
name = "data-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
axum = "0.8.7"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.1.5"
regex = "1.12.2"
serde = "1.0.228"
serde_json = "1.0.145"
sha2 = "0.10"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "sqlite", "macros", "uuid", "time"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal"] }
zstd = "0.13.3"
tower = "0.5"
tower-http = { version = "0.6.8", features = ["cors", "decompression-gzip", "decompression-zstd", "decompression-deflate", "decompression-br"] }
url = "2"
moka = { version = "0.12.12", features = ["sync", "future"] }
reqwest = { version = "0.13", features = ["json"] }
uuid = { version = "1.19.0", features = ["serde", "v4"] }
ua-parser = "0.2.1"
serde_yaml = "0.9.34"
metrics = "0.24"
metrics-exporter-prometheus = "0.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3"
rand = "0.10.0"
