use serde::Deserialize;
use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

#[path = "build/regex.rs"]
mod regex_rewrite;
use regex_rewrite::rewrite_regex;

const UAP_CORE_RULES: &str = "regexes.yaml";

#[derive(Deserialize)]
struct Rules {
    user_agent_parsers: Vec<ParserRule>,
    os_parsers: Vec<ParserRule>,
    device_parsers: Vec<DeviceRule>,
}

#[derive(Deserialize)]
struct ParserRule {
    regex: String,
    #[serde(alias = "family_replacement", alias = "os_replacement")]
    replacement: Option<String>,
    #[serde(alias = "os_v1_replacement")]
    v1_replacement: Option<String>,
    #[serde(alias = "os_v2_replacement")]
    v2_replacement: Option<String>,
}

#[derive(Deserialize)]
struct DeviceRule {
    regex: String,
    regex_flag: Option<String>,
    device_replacement: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed={UAP_CORE_RULES}");

    let source = Path::new(UAP_CORE_RULES);
    let yaml = fs::read_to_string(source)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", source.display()));
    let rules: Rules = serde_yaml_ng::from_str(&yaml)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", source.display()));
    let generated = generate(&rules);
    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set")).join("rules.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", output.display()));
}

fn generate(rules: &Rules) -> String {
    let mut output = String::from(
        "// @generated by crates/user-agent/build.rs from the vendored uap-core rules.\n\
         // Do not edit this file manually.\n\n\
         pub(crate) struct Rule {\n\
             pub regex: &'static str,\n\
             pub replacement: Option<&'static str>,\n\
             pub v1_replacement: Option<&'static str>,\n\
             pub v2_replacement: Option<&'static str>,\n\
         }\n\n\
         pub(crate) struct DeviceRule {\n\
             pub regex: &'static str,\n\
             pub is_bot: bool,\n\
         }\n\n",
    );

    generate_rules(&mut output, "UA_RULES", &rules.user_agent_parsers);
    generate_rules(&mut output, "OS_RULES", &rules.os_parsers);
    output.push_str("pub(crate) static DEVICE_RULES: &[DeviceRule] = &[\n");
    for rule in &rules.device_parsers {
        let regex = rewrite_regex(&rule.regex);
        let regex = if rule.regex_flag.as_deref() == Some("i") {
            format!("(?i:{regex})")
        } else {
            regex
        };
        writeln!(
            output,
            "    DeviceRule {{ regex: {}, is_bot: {} }},",
            literal(&regex),
            rule.device_replacement.as_deref() == Some("Spider"),
        )
        .unwrap();
    }
    output.push_str("];\n");
    output
}

fn generate_rules(output: &mut String, name: &str, rules: &[ParserRule]) {
    writeln!(output, "pub(crate) static {name}: &[Rule] = &[").unwrap();
    for rule in rules {
        writeln!(
            output,
            "    Rule {{ regex: {}, replacement: {}, v1_replacement: {}, v2_replacement: {} }},",
            literal(&rewrite_regex(&rule.regex)),
            optional_literal(rule.replacement.as_deref()),
            optional_literal(rule.v1_replacement.as_deref()),
            optional_literal(rule.v2_replacement.as_deref()),
        )
        .unwrap();
    }
    output.push_str("];\n\n");
}

fn optional_literal(value: Option<&str>) -> String {
    value.map_or_else(
        || "None".to_owned(),
        |value| format!("Some({})", literal(value)),
    )
}

fn literal(value: &str) -> String {
    format!("{value:?}")
}
