use serde::Deserialize;
use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

const UAP_CORE_RULES: &str = "regexes.yaml";

#[derive(Deserialize)]
struct Rules {
    user_agent_parsers: Vec<UserAgentRule>,
    os_parsers: Vec<OperatingSystemRule>,
    device_parsers: Vec<DeviceRule>,
}

#[derive(Deserialize)]
struct UserAgentRule {
    regex: String,
    family_replacement: Option<String>,
    v1_replacement: Option<String>,
    v2_replacement: Option<String>,
}

#[derive(Deserialize)]
struct OperatingSystemRule {
    regex: String,
    os_replacement: Option<String>,
    os_v1_replacement: Option<String>,
    os_v2_replacement: Option<String>,
}

#[derive(Deserialize)]
struct DeviceRule {
    regex: String,
    regex_flag: Option<String>,
    device_replacement: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed={UAP_CORE_RULES}");

    let source = Path::new(UAP_CORE_RULES);
    let yaml = fs::read_to_string(source)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", source.display()));
    let rules: Rules = serde_yaml::from_str(&yaml)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", source.display()));
    let generated = generate(&rules);
    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set")).join("rules.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", output.display()));
}

fn generate(rules: &Rules) -> String {
    let mut output = String::from(
        "// @generated by crates/user-agent/build.rs from the vendored uap-core rules.\n\
         // Do not edit this file manually.\n\n\
         pub(crate) struct Rule {\n\
             pub regex: &'static str,\n\
             pub replacement: Option<&'static str>,\n\
             pub v1_replacement: Option<&'static str>,\n\
             pub v2_replacement: Option<&'static str>,\n\
             pub ignore_case: bool,\n\
         }\n\n",
    );

    generate_rules(
        &mut output,
        "UA_RULES",
        rules.user_agent_parsers.iter().map(|rule| {
            (
                rule.regex.as_str(),
                rule.family_replacement.as_deref(),
                rule.v1_replacement.as_deref(),
                rule.v2_replacement.as_deref(),
                false,
            )
        }),
    );
    generate_rules(
        &mut output,
        "OS_RULES",
        rules.os_parsers.iter().map(|rule| {
            (
                rule.regex.as_str(),
                rule.os_replacement.as_deref(),
                rule.os_v1_replacement.as_deref(),
                rule.os_v2_replacement.as_deref(),
                false,
            )
        }),
    );
    generate_rules(
        &mut output,
        "DEVICE_RULES",
        rules.device_parsers.iter().map(|rule| {
            (
                rule.regex.as_str(),
                rule.device_replacement.as_deref(),
                None,
                None,
                rule.regex_flag.as_deref() == Some("i"),
            )
        }),
    );
    output
}

type GeneratedRule<'a> = (
    &'a str,
    Option<&'a str>,
    Option<&'a str>,
    Option<&'a str>,
    bool,
);

fn generate_rules<'a>(
    output: &mut String,
    name: &str,
    rules: impl Iterator<Item = GeneratedRule<'a>>,
) {
    writeln!(output, "pub(crate) static {name}: &[Rule] = &[").unwrap();
    for (regex, replacement, v1, v2, ignore_case) in rules {
        writeln!(
            output,
            "    Rule {{ regex: {}, replacement: {}, v1_replacement: {}, v2_replacement: {}, ignore_case: {ignore_case} }},",
            literal(regex),
            optional_literal(replacement),
            optional_literal(v1),
            optional_literal(v2),
        )
        .unwrap();
    }
    output.push_str("];\n\n");
}

fn optional_literal(value: Option<&str>) -> String {
    value.map_or_else(
        || "None".to_owned(),
        |value| format!("Some({})", literal(value)),
    )
}

fn literal(value: &str) -> String {
    for hashes in 1..=16 {
        let marker = "#".repeat(hashes);
        if !value.contains(&format!("\"{marker}")) {
            return format!("r{marker}\"{value}\"{marker}");
        }
    }
    panic!("could not create a raw Rust string literal")
}
