[package]
name = "collector-message"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
serde.workspace = true
uuid = { version = "1.26.1", features = ["serde", "v5"] }

[dev-dependencies]
serde_json.workspace = true
uuid = { version = "1.26.1", features = ["v4"] }
